### PR TITLE
 client: support writing to ONVIF back channels (#101) 

### LINKED ISSUE #101: Support ONVIF back channels
See section 5.3 of https://www.onvif.org/specs/stream/ONVIF-Streaming-Spec.pdf

### PR DESCRIPTION
**Pull request by aler9**
Fixes #101

### CODE REVIEW

**Comment by aler9** [comment]
@fjfeijoo i need confirmation from you that this patch works. Download the repository and check out this branch:

```
git clone https://github.com/bluenviron/gortsplib
cd gortsplib
git checkout feature/backchannels
```

then edit the `client-read-backchannel` example to point at your camera and start it:

```
go run ./examples/client-read-backchannel
```

**Comment by fjfeijoo** [comment]
@aler9 It's almost working. It plays the sound but after a few seconds it tries to switch to TCP because no UDP packets have been received. I suppose this is because doCheckTimeout doesn't support yet a "sending" only stream.

`user@pc gortsplib % go run ./examples/client-read-backchannel
2023/11/09 14:34:06 Waiting for a RTP/G711 stream on UDP port 9000 - you can send one with GStreamer:
gst-launch-1.0 audiotestsrc freq=300 ! audioconvert ! audioresample ! audio/x-raw,rate=8000 ! mulawenc ! rtppcmupay ! udpsink host=127.0.0.1 port=9000
2023/11/09 14:34:10 stream connected

---- PLAYS AUDIO OK ---

2023/11/09 14:34:13 no UDP packets received, switching to TCP

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1045fbac0]

goroutine 1 [running]:
github.com/bluenviron/gortsplib/v4.(*Client).WritePacketRTPWithNTP(0x140001286c0, 0x1400019c370, 0x140001621b0, {0x1046001c0?, 0x140001621b0?, 0x104913b40?})
	/Users/user/devel/gortsplib/client.go:1850 +0x150
github.com/bluenviron/gortsplib/v4.(*Client).WritePacketRTP(0x140001286c0, 0x14000156000?, 0x40c?)
	/Users/user/devel/gortsplib/client.go:1829 +0x4c
main.main()
	/Users/user/devel/gortsplib/examples/client-read-backchannel/main.go:105 +0x4e4
exit status 2`

**Comment by aler9** [comment]
thank you very much for the feedback. I've uploaded a fix for both issues, please check the branch again.

**Comment by cedricve** [comment]
Looking forward to see this, huge! :)

**Comment by aler9** [comment]
@cedricve @fjfeijoo i just need someone that confirms that this patch actually works on a real device, then i'll release ASAP.

**Comment by cedricve** [comment]
yes I'll have it tested this evening have a hikvision. Would be great to have an example MediaAPI (Microphone) to backchannel.

**Comment by cedricve** [comment]
which camera @fjfeijoo

**Comment by fjfeijoo** [comment]
Camera from Sunell (Chinese brand)

**Comment by cedricve** [comment]
Works on hikvision @aler9  @fjfeijoo

**Comment by cedricve** [comment]
@aler9 I'm trying out to read out a WAV file, and convert it so it can be send through your backchannel implementation. Do you have any experience with this? Might be more useful than reading from a stream created with gstreamer.

**Comment by cedricve** [comment]
Gave it a try (https://go.dev/play/p/1Seo_jakLnP), I recorded a .wav file 16000 samples, 16 bit. In the example I read the samples and encode to Alaw, then I create RTP packets of 1024bytes (encoded) and send it to the backchannel. I do here the tone of words, but there is a lot of noise, I also had to add a "sleep" to make sure it's played.

Not sure what I'm doing wrong, but would be cool to stream a pre-recorded audio file to the backchannel.

**Comment by cedricve** [comment]
After some more testing I found out, the "encoding to Alaw" is different and better with gstreamer `audioconvert ! audioresample ! audio/x-raw,rate=8000 ! mulawenc`. Will need to find a different to do the encoding as the `github.com/zaf/g711` library doesn't work as expected.

I confirmed this by exporting the output of the gstreamer command to a byte file, and sending it manually through the playground code mentioned above.

**Comment by aler9** [comment]
@cedricve i've improved the example and added GStreamer pipelines that allow to stream audio from the microphone or from a file.

Of course you can build a more complex script that streams audio from WebRTC / Media API or performs the PCMU conversion directly inside Go, but the aim of this library is to provide a dependency-free RTSP implementation, i can't add the pion/webrtc dependency or the zaf/g711 dependency.

**Comment by cedricve** [comment]
No worries, I do understand, overall your implementation works well. I'm just fiddling a bit around to have a similar approach as gstreamer mulaw encoder (PCM -> Mulaw) but then inside Go our Javascript.

**Comment by fjfeijoo** [comment]
Many thanks @aler9 !

**Pull request merged**
